## Pauli Matrices 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.array([[0,1],[1,0]])
np.linalg.eig(x)

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [5]:
y = np.array([[0,-1j],[1j,0]])
np.linalg.eig(y)

(array([ 1.+0.j, -1.+0.j]),
 array([[-0.        -0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [6]:
z = np.array([[1,0],[0,-1]])
np.linalg.eig(z)

(array([ 1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

## Normal Modes

In [8]:
w = np.array([[2,-1],[-1,2]]) ## W**2*m/k 값이 3, 1 을 가지게 된다.
np.linalg.eig(w)  # W**2*m/k 값이 3일때는 두 진자의 진폭은 같은 값 같은 방향, 1일때는 진폭값은 같고 방향은 반대방향

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))